# Generated by Django 5.2.9 on 2026-01-27 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_user_usersprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usersprofile'),
        ),
        migrations.AlterField(
            model_name='place',
            name='placename',
            field=models.CharField(max_length=1000),
        ),
    ]
